### ISSUE TITLE
Roots 4

### ISSUE THREAD

**Issue by benadamstyles** [carrot/roots-ignore#1]
`roots-ignore`'s `package.json` is preventing me from updating to Roots 4 in my project, due to the `peerinvalid` npm error (it wants Roots 3). I was putting together a PR for this repo to simply change `package.json` but then I got a `peerinvalid` for `roots-util`, which also wants Roots 3. Can you advise how best to go about solving this problem – are you guys planning to update the "core"/"contrib" extensions anytime soon, and if not, what's my best approach to tackling the `peerinvalid` errors? I'd like to start using Roots 4, not least because the BrowserSync notification is really slowing me down as I have navigation right in that spot! Thanks very much.

**Comment by hhsnopek** [comment]
Issue is located [here](https://github.com/carrot/roots-ignore/blob/master/package.json#L20)

**Comment by benadamstyles** [comment]
Yeah I know, but roots-util also wants 3.x, and before I went down the rabbit hole of following the chain of 3.x dependents I just wanted to check if I was missing something or if you had plans to update all roots-\* packages. But I'll give it a go today.

**Comment by benadamstyles** [comment]
My bad, looks like `roots-ignore` was referencing an old version of `roots-util` anyway, the latest version does depend on Roots 4.

**Comment by benadamstyles** [comment]
Has `0.0.2` been published to npm? Getting `npm ERR! version not found: roots-ignore@0.0.2`

**Comment by jescalan** [comment]
@Leeds-eBooks sorry, it was not, just published it now!

**Comment by benadamstyles** [comment]
@jenius Thanks!
